# -*- coding: utf-8 -*-
"""Image_compression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OmgVOekCps9EhyV9ktkMiRG-ba-rQKT5

# Here are 3 methods for resizing an image.
This will help you to reduce your file sizes and upload it wherever you want.
I am lettting you do some personalizations too.Other than handing over your photos to any websites, a simple python code will help you win the game.let's go...............
"""

import imageio

def compress_image(input_path, output_path, quality=20):
    img = imageio.imread(input_path)
    imageio.imwrite(output_path, img, quality=quality)

# Example usage
compress_image('input.jpg', 'output.jpg')

from PIL import Image

def compress_image(input_path, output_path, quality=20):
    with Image.open(input_path) as img:
        img.save(output_path, "JPEG", quality=quality)

# Example usage
compress_image('input.jpg', 'output.jpg')

import cv2

def compress_image(input_path, output_path, quality=20):
    img = cv2.imread(input_path)
    encode_param = [int(cv2.IMWRITE_JPEG_QUALITY), quality]
    cv2.imwrite(output_path, img, encode_param)

# Example usage
compress_image('input.jpg', 'output.jpg')